[package]
org = "ballerinax"
name = "mssql"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "SQLServer", "MSSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mssql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.1"

[[platform.java11.dependency]]
path = "../native/build/libs/mssql-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-@sql.native.version@.jar"

[[platform.java11.dependency]]
path = "./lib/mssql-jdbc-@mssqlDriverVersion@.jar"
scope = "testOnly"
