[package]
org = "ballerinax"
name = "mssql"
version = "1.5.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "SQLServer", "MSSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mssql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mssql-native"
version = "1.5.0"
path = "../native/build/libs/mssql-native-1.5.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.5.0"
path = "./lib/sql-native-1.5.0-20220906-153600-7e848e0.jar"

[[platform.java11.dependency]]
path = "./lib/mssql-jdbc-9.2.0.jre11.jar"
scope = "testOnly"
