[package]
org = "ballerinax"
name = "mssql"
version = "1.16.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "SQLServer", "MSSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mssql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mssql-native"
version = "1.16.0"
path = "../native/build/libs/mssql-native-1.16.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.16.0"
path = "./lib/sql-native-1.16.0.jar"
